services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: job_service
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    # build: . (Now we don't need to build the image because it already exist on the docker hub)
    image: rajatrulaniya/craon-backend:latest
    pull_policy: missing
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      MONGODB_URL: mongodb://admin:password@mongodb:27017
      MONGODB_DB: job_service
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      RATE_LIMIT_STORAGE_URL: redis://redis:6379/1
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    # build: .
    image: rajatrulaniya/craon-backend:latest
    pull_policy: missing
    environment:
      DEBUG: "True"
      MONGODB_URL: mongodb://admin:password@mongodb:27017
      MONGODB_DB: job_service
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      RATE_LIMIT_STORAGE_URL: redis://redis:6379/1
    depends_on:
      - redis
      - mongodb
      - server
    command: celery -A worker worker --loglevel=info -c 4

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=http://craon.rajatrulaniya.com/prometheus"
      - "--web.route-prefix=/Prometheus"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://craon.rajatrulaniya.com/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:
