global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090/prometheus/metrics"]

  - job_name: "task_queue_service"
    static_configs:
      - targets: ["server:8000/metrics"]