{
 "title": "Craon task-queue-service Dashboard",
 "description": "Stat Panels",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Executive Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Queue Depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "job_queue_depth", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Jobs Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "jobs_completed_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Jobs Enqueued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "jobs_enqueued_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "API Error Rate (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(http_requests_total{status=\"5xx\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker & Queue Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "New panelThroughput (Enqueued vs Completed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "expr": "rate(jobs_enqueued_total[5m])", "legendFormat": "__auto" },
      { "expr": "rate(jobs_completed_total[5m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Queue Depth Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      { "expr": "job_queue_depth", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Processing Duration p95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(job_processing_duration_seconds_bucket[5m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API & Web Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(handler) (rate(http_requests_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "All client errors (4xx)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{status=\"4xx\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}